{% set name = "s_gd2" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 977597da6d7f6f4b7a479732e374e48d34369e047090720c5d78ca3ca59dc269

build:
  number: 4
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=1.16.0                         # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
  host:
    - python
    - pip
    - numpy >=1.16.0
    - cython
  run:
    - python

test:
  imports:
    - s_gd2

about:
  home: https://github.com/jxz12/s_gd2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Stochastic Gradient Descent for Graph Drawing

  description: |
    Stochastic Gradient Descent for Graph Drawing [arXiv:1710.04626]. 
    A video of the corresponding talk (given at IEEE VIS 2019) can be viewed at vimeo.com/373015168.
  dev_url: https://github.com/jxz12/s_gd2

extra:
  recipe-maintainers:
    - jxz12
    - scottgigante
